### PR TITLE
Outline for SV from Manting

### PR DESCRIPTION
**Pull request by mantihuang**
1. List the outline for SV part
2. Add two new references for SV

### CODE REVIEW

**Comment by donotdespair** [comment]
Hi @mantihuang 

It's looking good thus far. When you decide that that's it for your submission just send the link on Canvas and maybe let me know in a message here! Thank you!

T

**Comment by mantihuang** [comment]
Hi @donotdespair ,

@Eung1 and I have made revisions to this section. Could you please review it and provide any feedback? 

Thank you very much.

Best,
@mantihuang

**Comment by donotdespair** [comment]
Hey @mantihuang and @Eung1 

Thanks so much for this work! I went through the sections updating the notation to align it with the rest of the article. 

I have rewritten the model equations and the likelihood. Now, they're correct. I believe that you'd need to update the derivations a bit. Would you also please state the equation for $h_t$? Whichever form you choose (probably the random walk equation, as it results in fewer parameters to estimate).

Cheers @donotdespair

**Comment by Eung1** [comment]
Hi @donotdespair 

Thanks for the comment and help! Can I ask a clarification question? Are the derivations required about the essential techniques part, so, auxiliary mixture and precision sampler?

Best, 

@Eung1

**Comment by Eung1** [comment]
Hi @donotdespair

Sorry I didn't include @mantihuang in the previous comment. So I'm rewriting it again.
Thanks for the comment and help! Can I ask a clarification question? Are the derivations required about the essential techniques part, so, auxiliary mixture and precision sampler?

Best,

@Eung1

**Comment by donotdespair** [comment]
Nope! :)

**Comment by donotdespair** [comment]
Hey @mantihuang and @Eung1 Is this finished now? Can I merge PR #18? Please let me know. Thanks! T

**Comment by Eung1** [comment]
Hi @donotdespair,

Yes. This is our final version.

Best

@Eung1 and @mantihuang

**Comment by donotdespair** [comment]
Hey @mantihuang and @Eung1 

Thanks for the submission! I really appreciate it! I have introduced quite some corrections in the notation, descriptions, and code.

Greetings, T

**Pull request merged**
