### PR TITLE
Contribution to the learning repository from Thomas & Jonas

### PR DESCRIPTION
**Pull request by jonasld23**
Hi @donotdespair ,

We hope you are well. 

Please check out our contribution (7bb6e3575148d8f6ef07bdadd64712465e00c470) to the learning repository, which includes the following subsections:

- Likelihood as normal-inverted gamma 2
- Normal-inverted gamma 2 prior
- Normal-inverted gamma 2 posterior
- Sampling draws from the posterior

All the best!

Kind regards, 
The Danish vikings (@ThomasKronhol & @jonasld23 )

### CODE REVIEW

**Comment by donotdespair** [comment]
Hey @ThomasKronhol and @jonasld23 

Thank you for your swift submission! I really appreciate this!

May I ask for the following changes:

- [x] rewrite your note for `k = d+p` and not `k=1` (or `N=1`) as you stated in the note

I would greatly appreciate this, as the requirement of this assignment is to make the notes compatible with the first section [Autoregressions](https://donotdespair.github.io/Bayesian-Autoregressions/#autoregressions). Please note that you can simply reuse your solutions for Test 2. To sweeten the deal, I did not really ask for derivations. So, please

- [x] state the likelihood as the NIG2 distribution with the corresponding parameters
- [x] state the kernel of the posterior as the likelihood times the joint prior, also using the corresponding pdfs
- [x] skip the derivations
- [x] state the joint nig2 posterior and its parameters
- [x] adjust the sampling code

I would greatly appreciate this!

@donotdespair

**Comment by donotdespair** [comment]
Hey @jonasld23 and @ThomasKronhol 

Probably I should have mentioned... that you can, of course, decide that this is your submission and that's it. It will be reflected in a slightly lower grade for this part, though. 

If you want to include the upgrade, then commit to this Pull Request. If not just let me know here.

**Comment by ThomasKronhol** [comment]
Hi @donotdespair 

We will of course have a look at it! 

Best
T

**Comment by jonasld23** [comment]
Hey @donotdespair 

We have now committed the changes. 

The notation should be aligned with the first section now and hopefully everything is correct. 

Please feel free to reach out if not.

Kind regards,

@jonasld23 @ThomasKronhol

**Pull request merged**
